### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'

### ISSUE THREAD

**Issue by huanhoang2121** [aminyazdanpanah/python-ffmpeg-video-streaming#120]
**Describe the bug**
I use Odoo 14, with docker
In docker file:
     RUN pip3 install python-ffmpeg-video-streaming
When I get the above error, I have more: RUN pip3 install ffmpeg-python but can't

**Logs**
2023-06-09 09:36:03,411 1 INFO djc root: /mnt/extra-addons/djc_library/static/files/slide/95/mov_bbb.mp4 
2023-06-09 09:36:03,412 1 INFO djc root: <ffmpeg_streaming._input.Input object at 0x7f0d2c354978> 
2023-06-09 09:36:03,413 1 INFO djc root: <ffmpeg_streaming._media.DASH object at 0x7f0d2c330ba8> 
2023-06-09 09:36:03,415 1 INFO djc root: [Errno 17] File exists: '/mnt/extra-addons/djc_library/static/files/slide/95' 
2023-06-09 09:36:03,416 1 INFO djc root: ffmpeg running command: ffmpeg -y -i /djc_library/static/files/slide/95/mov_bbb.mp4 -c:v libx264 -c:a aac -bf 1 -keyint_min 25 -g 250 -sc_threshold 40 -use_timeline 1 -use_template 1 -init_seg_name mov_bbb_init_$RepresentationID$.$ext$ -media_seg_name mov_bbb_chunk_$RepresentationID$_$Number%05d$.$ext$ -f dash -map 0 -s:v:0 256x144 -b:v:0 95k -b:a:0 64k -map 0 -s:v:1 426x240 -b:v:1 150k -b:a:1 94k -map 0 -s:v:2 640x360 -b:v:2 276k -b:a:2 128k -map 0 -s:v:3 854x480 -b:v:3 750k -b:a:3 192k -map 0 -s:v:4 1280x720 -b:v:4 2048k -b:a:4 320k -map 0 -s:v:5 1920x1080 -b:v:5 4096k -b:a:5 320k -map 0 -s:v:6 2560x1440 -b:v:6 6144k -b:a:6 320k -map 0 -s:v:7 3840x2160 -b:v:7 17408k -b:a:7 320k -strict -2 /mnt/extra-addons/djc_library/static/files/slide/95/mov_bbb.mpd 
2023-06-09 09:36:03,422 1 ERROR djc odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1370, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/djc_library/models/slide_channel.py", line 451, in write
    chanel = super().write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/website_slides/models/slide_channel.py", line 416, in write
    res = super(Channel, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 322, in write
    result = super(MailThread, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/rating/models/rating_mixin.py", line 82, in write
    result = super(RatingMixin, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_activity.py", line 788, in write
    return super(MailActivityMixin, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/mixins.py", line 205, in write
    return super(WebsitePublishedMixin, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3681, in write
    field.write(self, vals[fname])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3057, in write
    return self.write_batch([(records, value)])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3078, in write_batch
    return self.write_real(records_commands_list, create)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3233, in write_real
    comodel.browse(command[1]).write(command[2])
  File "/mnt/extra-addons/djc_library/models/slide_slide.py", line 390, in write
    self.local_file(self)
  File "/mnt/extra-addons/djc_library/models/slide_slide.py", line 465, in local_file
    dash.output(file_path.replace('.mp4', '.mpd'))
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_streaming/_media.py", line 93, in output
    self.run(ffmpeg_bin, monitor, **options)
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_streaming/_media.py", line 121, in run
    asyncio.run(self.async_run(ffmpeg_bin, monitor, **options))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_streaming/_media.py", line 112, in async_run
    self._run(ffmpeg_bin, monitor, **options)
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_streaming/_media.py", line 105, in _run
    with Process(self, command_builder(ffmpeg_bin, self), monitor, **options) as process:
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_streaming/_process.py", line 58, in __init__
    self.process = _p_open(commands, **options)
  File "/usr/local/lib/python3.7/dist-packages/ffmpeg_streaming/_process.py", line 29, in _p_open
    return subprocess.Popen(shlex.split(commands), **options)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'

**Comment by mangeshchavan** [comment]
you need to install ffmpeg into your docker file like : 

**RUN apt-get update && apt-get install -y  ffmpeg**
