### ISSUE TITLE
RuntimeError: asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by csrujan** [aminyazdanpanah/python-ffmpeg-video-streaming#25]
runfile('C:/Users/schalava.PARTNERS/Downloads/Projects/Python/DEMOlive/notworking_because_of_ffmpegstreaming_version_dash015p.py', wdir='C:/Users/schalava.PARTNERS/Downloads/Projects/Python/DEMOlive')
Traceback (most recent call last):

  File "<ipython-input-1-e0244f5848ad>", line 1, in <module>
    runfile('C:/Users/schalava.PARTNERS/Downloads/Projects/Python/DEMOlive/notworking_because_of_ffmpegstreaming_version_dash015p.py', wdir='C:/Users/schalava.PARTNERS/Downloads/Projects/Python/DEMOlive')

  File "C:\Users\schalava.PARTNERS\AppData\Local\Continuum\anaconda3\envs\dashpy\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\schalava.PARTNERS\AppData\Local\Continuum\anaconda3\envs\dashpy\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/schalava.PARTNERS/Downloads/Projects/Python/DEMOlive/notworking_because_of_ffmpegstreaming_version_dash015p.py", line 33, in <module>
    dash.output('/test212.mpd')

  File "C:\Users\schalava.PARTNERS\AppData\Local\Continuum\anaconda3\envs\dashpy\lib\site-packages\ffmpeg_streaming\_media.py", line 85, in output
    asyncio.run(self._run(ffmpeg_bin, monitor, **options))

  File "C:\Users\schalava.PARTNERS\AppData\Local\Continuum\anaconda3\envs\dashpy\lib\asyncio\runners.py", line 34, in run
    "asyncio.run() cannot be called from a running event loop")

RuntimeError: asyncio.run() cannot be called from a running event loop

**Comment by aminyazdanpanah** [comment]
Try this:
``` python
dash.output('/test212.mpd', async_run=False)
```
