### ISSUE TITLE
run on pythonanywhere.com,ffmpeg failed to execute command,Option not found

### ISSUE THREAD

**Issue by makelove** [aminyazdanpanah/python-ffmpeg-video-streaming#46]
## my code
```
    video = ffmpeg_streaming.input(fp)
    hls = video.hls(Formats.h264())
    hls.representations(_360p)
    hls.output('~/video/t1.m3u8')
```

## output
```
ERROR:root:ffmpeg failed to execute command: b"ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers\n  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609\n  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv\n  libavutil      54. 31.100 / 54. 31.100\n  libavcodec     56. 60.100 / 56. 60.100\n  libavformat    56. 40.101 / 56. 40.101\n  libavdevice    56.  4.100 / 56.  4.100\n  libavfilter     5. 40.101 /  5. 40.101\n  libavresample   2.  1.  0 /  2.  1.  0\n  libswscale      3.  1.101 /  3.  1.101\n  libswresample   1.  2.101 /  1.  2.101\n  libpostproc    53.  3.100 / 53.  3.100\nUnrecognized option 'hls_fmp4_init_filename'.\nError splitting the argument list: Option not found\n"
Traceback (most recent call last):
  File "../m3u8cmd.py", line 29, in <module>
    main(sys.argv[1])
  File "../m3u8cmd.py", line 23, in main
    hls.output('~/video/t1.m3u8')
  File "/home/ytgl/.local/lib/python3.8/site-packages/ffmpeg_streaming/_media.py", line 93, in output
    self.run(ffmpeg_bin, monitor, **options)
  File "/home/ytgl/.local/lib/python3.8/site-packages/ffmpeg_streaming/_media.py", line 121, in run
    asyncio.run(self.async_run(ffmpeg_bin, monitor, **options))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/home/ytgl/.local/lib/python3.8/site-packages/ffmpeg_streaming/_media.py", line 112, in async_run
    self._run(ffmpeg_bin, monitor, **options)
  File "/home/ytgl/.local/lib/python3.8/site-packages/ffmpeg_streaming/_media.py", line 106, in _run
    self.pipe, err = process.run()
  File "/home/ytgl/.local/lib/python3.8/site-packages/ffmpeg_streaming/_process.py", line 122, in run
    raise RuntimeError('ffmpeg failed to execute command: ', error)
RuntimeError: ('ffmpeg failed to execute command: ', 'b"ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers\\n  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609\\n  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv\\n  libavutil      54. 31.100 / 54. 31.100\\n  libavcodec     56. 60.100 / 56. 60.100\\n  libavformat    56. 40.101 / 56. 40.101\\n  libavdevice    56.  4.100 / 56.  4.100\\n  libavfilter     5. 40.101 /  5. 40.101\\n  libavresample   2.  1.  0 /  2.  1.  0\\n  libswscale      3.  1.101 /  3.  1.101\\n  libswresample   1.  2.101 /  1.  2.101\\n  libpostproc    53.  3.100 / 53.  3.100\\nUnrecognized option \'hls_fmp4_init_filename\'.\\nError splitting the argument list: Option not found\\n"')

```

Why ?
How to solve it ?

**Comment by maddigibiter** [comment]
Check if you have latest FFMPEG installed

**Comment by aminyazdanpanah** [comment]
The `hls_fmp4_init_filename` option is not supported in some versions of FFmpeg.

Update your FFmpeg and try it again.
