### ISSUE TITLE
recursion error occurred while using S3 for the input

### ISSUE THREAD

**Issue by mojtaba-arvin** [aminyazdanpanah/python-ffmpeg-video-streaming#54]
**Describe the bug**
a recursion error occurred while using S3 for the input after call hls
 
**To Reproduce**
This is a sample code to generate the error:

```
import ffmpeg_streaming
from ffmpeg_streaming import Formats, S3

s3 = S3(
    endpoint_url="*********************",
    aws_access_key_id="****************",
    aws_secret_access_key="************",
    region_name="us-east-1",
    use_ssl=False
)

video = ffmpeg_streaming.input(s3, bucket_name="foo", key="bar.mp4")
hls = video.hls(Formats.h264())
```

and this is the Traceback of Recursion Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/ffmpeg_streaming/_input.py", line 139, in method
    media = Media(self)
  File "/usr/local/lib/python3.9/site-packages/ffmpeg_streaming/_media.py", line 246, in __init__
    first_input = dict(copy.deepcopy(_inputs.inputs[0]))
  File "/usr/local/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)

  ...

  File "/usr/local/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.9/copy.py", line 271, in _reconstruct
    if hasattr(y, '__setstate__'):
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 606, in __getattr__
    self._service_model.service_id.hyphenize(), item
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 629, in _service_model
    return self.meta.service_model
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 606, in __getattr__
    self._service_model.service_id.hyphenize(), item
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 629, in _service_model
    return self.meta.service_model
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 606, in __getattr__
    self._service_model.service_id.hyphenize(), item
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 629, in _service_model
    return self.meta.service_model

  ...
  
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 606, in __getattr__
    self._service_model.service_id.hyphenize(), item
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 629, in _service_model
    return self.meta.service_model
  RecursionError: maximum recursion depth exceeded
```

**Local machine :**
 - Python 3.9.2
 - FFMpeg 4.1
 - boto3 1.17.14
 - botocore 1.20.14
 - python-ffmpeg-video-streaming 0.1.14

thanks for your awesome package :+1:

**Comment by PyWoo** [comment]
Hi, I'm seeing the same issue, and was wondering if you ever found a resolution to this?

**Comment by aminyazdanpanah** [comment]
same as #49 
I will check this issue later.
Maybe the problem is related to [this line](https://github.com/aminyazdanpanah/python-ffmpeg-video-streaming/blob/731530fd9e569362f9ba30d723b395bf0d011eb3/ffmpeg_streaming/_media.py#L246).

**Comment by zhanymkanov** [comment]
Have the exact same problem. I see no reason to deepcopy the input dict, since we only `get` the data without modifications. Moreover, deepcopy is a heavy CPU operation. I suggest to skip it. 

If not, I believe there is a problem in S3 download method. I will try to check that out.

**Comment by ShakeelAhmad-dev** [comment]
Any about or solution of this error ?

**Comment by RichardDally** [comment]
`copy.copy` seems to fix the issue, at least for my case...

**Comment by RichardDally** [comment]
@aminyazdanpanah if you are ok with the fix, please merge when you got some time :)

**Comment by aminyazdanpanah** [comment]
Please Update the package

``` python
pip install --upgrade python-ffmpeg-video-streaming
```
