### ISSUE TITLE
cannot schedule new futures after interpreter shutdown when use cloud (s3) to upload outputs 

### ISSUE THREAD

**Issue by hirakhax** [aminyazdanpanah/python-ffmpeg-video-streaming#79]
** Error Log
```
app_1  | Error in atexit._run_exitfuncs:
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.8/site-packages/ffmpeg_streaming/_clouds.py", line 59, in upload_directory
app_1  |     self.s3.upload_file(join(directory, file), bucket_name, join(folder, file).replace("\\", "/"))
app_1  |   File "/usr/local/lib/python3.8/site-packages/boto3/s3/inject.py", line 143, in upload_file
app_1  |     return transfer.upload_file(
app_1  |   File "/usr/local/lib/python3.8/site-packages/boto3/s3/transfer.py", line 284, in upload_file
app_1  |     future = self._manager.upload(
app_1  |   File "/usr/local/lib/python3.8/site-packages/s3transfer/manager.py", line 330, in upload
app_1  |     return self._submit_transfer(
app_1  |   File "/usr/local/lib/python3.8/site-packages/s3transfer/manager.py", line 525, in _submit_transfer
app_1  |     self._submission_executor.submit(
app_1  |   File "/usr/local/lib/python3.8/site-packages/s3transfer/futures.py", line 474, in submit
app_1  |     future = ExecutorFuture(self._executor.submit(task))
app_1  |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 181, in submit
app_1  |     raise RuntimeError('cannot schedule new futures after '
app_1  | RuntimeError: cannot schedule new futures after interpreter shutdown
hls_transcoder_pro_app_1 exited with code 0
```

**Comment by mangeshchavan** [comment]
I am also facing same issue ,please do needful

**Comment by Aryan-dvlp2** [comment]
I am also facing the same issue!! 
Can anyone help me?

**Comment by aminyazdanpanah** [comment]
Thank you for the report.
I am going to refactor this library and I will consider your bug report
