### ISSUE TITLE
RuntimeError: It could not determine the value of bitrate

### ISSUE THREAD

**Issue by SeaDude** [aminyazdanpanah/python-ffmpeg-video-streaming#86]
Hello,

Working through the Quick start with...

1. Install the Windows binaries (`ffmpeg` and `ffprobe`)
2. Add the `bin` dir to `Path` env variable, restart

![image](https://user-images.githubusercontent.com/8636973/173152625-9858b9de-0f30-46fb-918a-29cf73df9b7e.png)

4. Create a new `.venv` and activate it
5. `pip install python-ffmpeg-video-streaming`
6. Create a new `test.py` file with...

```
import ffmpeg_streaming
from ffmpeg_streaming import Formats


video = ffmpeg_streaming.input('rtsp://192.168.0.22:554/s0')

hls = video.hls(Formats.h264())
hls.auto_generate_representations()

hls.output()
```
7. Run `python test.py` in terminal

**Error:**

```
Traceback (most recent call last):
  File "E:\test.py", line 8, in <module>
    hls.auto_generate_representations()
  File "E:\.venv\lib\site-packages\ffmpeg_streaming\_media.py", line 143, in 
auto_generate_representations
    self.reps = AutoRep(probe.video_size, probe.bitrate, self.format, heights, bitrate, include_original)    
  File "E:\.venv\lib\site-packages\ffmpeg_streaming\ffprobe.py", line 141, in bitrate
    raise RuntimeError('It could not determine the value of bitrate')
RuntimeError: It could not determine the value of bitrate
```

**Any leads on how to debug this?**

Thank you

**Comment by aminyazdanpanah** [comment]
The error message means 'FFprobe cannot get original overall bitrate'. 

You can use `representations` instead of using `auto_generate_representations` method.

``` python
 import ffmpeg_streaming
from ffmpeg_streaming import Formats

#_360p  = Representation(Size(640, 360), Bitrate(276 * 1024, 128 * 1024))
_480p  = Representation(Size(854, 480), Bitrate(750 * 1024, 192 * 1024))
#_720p  = Representation(Size(1280, 720), Bitrate(2048 * 1024, 320 * 1024))

video = ffmpeg_streaming.input('rtsp://192.168.0.22:554/s0')
hls = video.hls(Formats.h264())

#hls.auto_generate_representations()
hls.representations(_480p)

hls.output()
```
